name: windows
on: [push, pull_request]

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        arch: [x64]
        image: [windows-2019]
        compiler: [cl]
        std: [14]
        config: [debug, release]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout vcpkg
        uses: actions/checkout@v2
        with:
          repository: microsoft/vcpkg
          path: vcpkg

      - name: Install ninja
        run: choco install ninja -y

      - name: Setup MSVC Environment
        if: runner.os == 'Windows'
        run: |
          $vcvarsall = "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvarsall.bat"
          cmd /c "`"$vcvarsall`" ${{ matrix.arch }} > nul 2>&1 && set" >> $Env:GITHUB_ENV
          exit $LASTEXITCODE

      - name: Configure
        env:
          VCPKG_ROOT: ${{ github.workspace }}/vcpkg
        run: >
          cmake
          --preset ${{ matrix.arch }}-windows-${{ matrix.compiler }}-std${{ matrix.std }}-${{ matrix.config }}
          -B out/build
          .

      - name: Build
        run: cmake --build out/build

      - name: Test
        working-directory: out/build
        run: ctest --verbose --output-on-failure
